/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiDashboardRouteImport } from './routes/api-dashboard'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TacticsIndexRouteImport } from './routes/tactics.index'
import { Route as StudyIndexRouteImport } from './routes/study.index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as OpeningsIndexRouteImport } from './routes/openings.index'
import { Route as LessonsIndexRouteImport } from './routes/lessons.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as EndgameIndexRouteImport } from './routes/endgame.index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TacticsThemeRouteImport } from './routes/tactics.$theme'
import { Route as StudyStudyIdRouteImport } from './routes/study.$studyId'
import { Route as PuzzlesStormRouteImport } from './routes/puzzles.storm'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as OpeningsEcoRouteImport } from './routes/openings.$eco'
import { Route as LessonsIdRouteImport } from './routes/lessons.$id'
import { Route as LearnTutorialIdRouteImport } from './routes/learn.$tutorialId'
import { Route as EndgameIdRouteImport } from './routes/endgame.$id'
import { Route as CoachingDashboardRouteImport } from './routes/coaching.dashboard'
import { Route as CoachesCoachIdRouteImport } from './routes/coaches.$coachId'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrgsRouteImport } from './routes/admin.orgs'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminCoachesRouteImport } from './routes/admin.coaches'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as PuzzlesDailyDateRouteImport } from './routes/puzzles.daily.$date'
import { Route as EmbedKindTokenRouteImport } from './routes/embed.$kind.$token'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as ApiPublicV1WebhooksRouteImport } from './routes/api/public/v1/webhooks'
import { Route as ApiPublicV1TournamentsRouteImport } from './routes/api/public/v1/tournaments'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack.webhook'
import { Route as ApiPublicV1WebhooksRetrySweepRouteImport } from './routes/api/public/v1/webhooks.retry-sweep'
import { Route as ApiPublicV1WebhooksIdRouteImport } from './routes/api/public/v1/webhooks.$id'
import { Route as ApiPublicV1EmbedTokenRouteImport } from './routes/api/public/v1/embed.token'
import { Route as ApiPublicV1CorrespondenceSweepRouteImport } from './routes/api/public/v1/correspondence.sweep'
import { Route as ApiPublicV1ClassesSessionRouteImport } from './routes/api/public/v1/classes.session'
import { Route as ApiPublicV1UsersUsernameRatingRouteImport } from './routes/api/public/v1/users.$username.rating'
import { Route as ApiPublicV1UsersUsernameGamesRouteImport } from './routes/api/public/v1/users.$username.games'
import { Route as ApiPublicV1TournamentsIdStandingsRouteImport } from './routes/api/public/v1/tournaments.$id.standings'
import { Route as ApiPublicV1EmbedTokenTokenRouteImport } from './routes/api/public/v1/embed.token.$token'
import { Route as ApiPublicV1ClassesSessionIdStudentsRouteImport } from './routes/api/public/v1/classes.session.$id.students'
import { Route as ApiPublicV1ClassesSessionIdSetPositionRouteImport } from './routes/api/public/v1/classes.session.$id.set-position'

const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api-dashboard',
  path: '/api-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TacticsIndexRoute = TacticsIndexRouteImport.update({
  id: '/tactics/',
  path: '/tactics/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsIndexRoute = OpeningsIndexRouteImport.update({
  id: '/openings/',
  path: '/openings/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgameIndexRoute = EndgameIndexRouteImport.update({
  id: '/endgame/',
  path: '/endgame/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TacticsThemeRoute = TacticsThemeRouteImport.update({
  id: '/tactics/$theme',
  path: '/tactics/$theme',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyStudyIdRoute = StudyStudyIdRouteImport.update({
  id: '/study/$studyId',
  path: '/study/$studyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesStormRoute = PuzzlesStormRouteImport.update({
  id: '/puzzles/storm',
  path: '/puzzles/storm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsEcoRoute = OpeningsEcoRouteImport.update({
  id: '/openings/$eco',
  path: '/openings/$eco',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIdRoute = LessonsIdRouteImport.update({
  id: '/lessons/$id',
  path: '/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTutorialIdRoute = LearnTutorialIdRouteImport.update({
  id: '/learn/$tutorialId',
  path: '/learn/$tutorialId',
  getParentRoute: () => rootRouteImport,
} as any)
const EndgameIdRoute = EndgameIdRouteImport.update({
  id: '/endgame/$id',
  path: '/endgame/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingDashboardRoute = CoachingDashboardRouteImport.update({
  id: '/coaching/dashboard',
  path: '/coaching/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesCoachIdRoute = CoachesCoachIdRouteImport.update({
  id: '/coaches/$coachId',
  path: '/coaches/$coachId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoachesRoute = AdminCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const PuzzlesDailyDateRoute = PuzzlesDailyDateRouteImport.update({
  id: '/puzzles/daily/$date',
  path: '/puzzles/daily/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKindTokenRoute = EmbedKindTokenRouteImport.update({
  id: '/embed/$kind/$token',
  path: '/embed/$kind/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicV1WebhooksRoute = ApiPublicV1WebhooksRouteImport.update({
  id: '/api/public/v1/webhooks',
  path: '/api/public/v1/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TournamentsRoute = ApiPublicV1TournamentsRouteImport.update({
  id: '/api/public/v1/tournaments',
  path: '/api/public/v1/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack/webhook',
    path: '/api/public/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1WebhooksRetrySweepRoute =
  ApiPublicV1WebhooksRetrySweepRouteImport.update({
    id: '/retry-sweep',
    path: '/retry-sweep',
    getParentRoute: () => ApiPublicV1WebhooksRoute,
  } as any)
const ApiPublicV1WebhooksIdRoute = ApiPublicV1WebhooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1WebhooksRoute,
} as any)
const ApiPublicV1EmbedTokenRoute = ApiPublicV1EmbedTokenRouteImport.update({
  id: '/api/public/v1/embed/token',
  path: '/api/public/v1/embed/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CorrespondenceSweepRoute =
  ApiPublicV1CorrespondenceSweepRouteImport.update({
    id: '/api/public/v1/correspondence/sweep',
    path: '/api/public/v1/correspondence/sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ClassesSessionRoute =
  ApiPublicV1ClassesSessionRouteImport.update({
    id: '/api/public/v1/classes/session',
    path: '/api/public/v1/classes/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1UsersUsernameRatingRoute =
  ApiPublicV1UsersUsernameRatingRouteImport.update({
    id: '/api/public/v1/users/$username/rating',
    path: '/api/public/v1/users/$username/rating',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1UsersUsernameGamesRoute =
  ApiPublicV1UsersUsernameGamesRouteImport.update({
    id: '/api/public/v1/users/$username/games',
    path: '/api/public/v1/users/$username/games',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1TournamentsIdStandingsRoute =
  ApiPublicV1TournamentsIdStandingsRouteImport.update({
    id: '/$id/standings',
    path: '/$id/standings',
    getParentRoute: () => ApiPublicV1TournamentsRoute,
  } as any)
const ApiPublicV1EmbedTokenTokenRoute =
  ApiPublicV1EmbedTokenTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiPublicV1EmbedTokenRoute,
  } as any)
const ApiPublicV1ClassesSessionIdStudentsRoute =
  ApiPublicV1ClassesSessionIdStudentsRouteImport.update({
    id: '/$id/students',
    path: '/$id/students',
    getParentRoute: () => ApiPublicV1ClassesSessionRoute,
  } as any)
const ApiPublicV1ClassesSessionIdSetPositionRoute =
  ApiPublicV1ClassesSessionIdSetPositionRouteImport.update({
    id: '/$id/set-position',
    path: '/$id/set-position',
    getParentRoute: () => ApiPublicV1ClassesSessionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/endgame/': typeof EndgameIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/admin': typeof AdminIndexRoute
  '/assistant': typeof AssistantIndexRoute
  '/coaches': typeof CoachesIndexRoute
  '/endgame': typeof EndgameIndexRoute
  '/learn': typeof LearnIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/openings': typeof OpeningsIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/study': typeof StudyIndexRoute
  '/tactics': typeof TacticsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/api-dashboard': typeof ApiDashboardRoute
  '/billing': typeof BillingRoute
  '/feed': typeof FeedRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lobby': typeof LobbyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/coaches': typeof AdminCoachesRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/coaches/$coachId': typeof CoachesCoachIdRoute
  '/coaching/dashboard': typeof CoachingDashboardRoute
  '/endgame/$id': typeof EndgameIdRoute
  '/learn/$tutorialId': typeof LearnTutorialIdRoute
  '/lessons/$id': typeof LessonsIdRoute
  '/openings/$eco': typeof OpeningsEcoRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/puzzles/storm': typeof PuzzlesStormRoute
  '/study/$studyId': typeof StudyStudyIdRoute
  '/tactics/$theme': typeof TacticsThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/assistant/': typeof AssistantIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/endgame/': typeof EndgameIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/openings/': typeof OpeningsIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/study/': typeof StudyIndexRoute
  '/tactics/': typeof TacticsIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/embed/$kind/$token': typeof EmbedKindTokenRoute
  '/puzzles/daily/$date': typeof PuzzlesDailyDateRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/api/public/paystack/webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/v1/tournaments': typeof ApiPublicV1TournamentsRouteWithChildren
  '/api/public/v1/webhooks': typeof ApiPublicV1WebhooksRouteWithChildren
  '/api/public/v1/classes/session': typeof ApiPublicV1ClassesSessionRouteWithChildren
  '/api/public/v1/correspondence/sweep': typeof ApiPublicV1CorrespondenceSweepRoute
  '/api/public/v1/embed/token': typeof ApiPublicV1EmbedTokenRouteWithChildren
  '/api/public/v1/webhooks/$id': typeof ApiPublicV1WebhooksIdRoute
  '/api/public/v1/webhooks/retry-sweep': typeof ApiPublicV1WebhooksRetrySweepRoute
  '/api/public/v1/embed/token/$token': typeof ApiPublicV1EmbedTokenTokenRoute
  '/api/public/v1/tournaments/$id/standings': typeof ApiPublicV1TournamentsIdStandingsRoute
  '/api/public/v1/users/$username/games': typeof ApiPublicV1UsersUsernameGamesRoute
  '/api/public/v1/users/$username/rating': typeof ApiPublicV1UsersUsernameRatingRoute
  '/api/public/v1/classes/session/$id/set-position': typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  '/api/public/v1/classes/session/$id/students': typeof ApiPublicV1ClassesSessionIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/feed'
    | '/insights'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/admin/'
    | '/assistant/'
    | '/coaches/'
    | '/endgame/'
    | '/learn/'
    | '/lessons/'
    | '/openings/'
    | '/puzzles/'
    | '/study/'
    | '/tactics/'
    | '/admin/users/$userId'
    | '/embed/$kind/$token'
    | '/puzzles/daily/$date'
    | '/admin/users/'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/feed'
    | '/insights'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/admin'
    | '/assistant'
    | '/coaches'
    | '/endgame'
    | '/learn'
    | '/lessons'
    | '/openings'
    | '/puzzles'
    | '/study'
    | '/tactics'
    | '/admin/users/$userId'
    | '/embed/$kind/$token'
    | '/puzzles/daily/$date'
    | '/admin/users'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/api-dashboard'
    | '/billing'
    | '/feed'
    | '/insights'
    | '/leaderboard'
    | '/lobby'
    | '/login'
    | '/messages'
    | '/admin/audit-log'
    | '/admin/coaches'
    | '/admin/games'
    | '/admin/orgs'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/roles'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/coaches/$coachId'
    | '/coaching/dashboard'
    | '/endgame/$id'
    | '/learn/$tutorialId'
    | '/lessons/$id'
    | '/openings/$eco'
    | '/play/$gameId'
    | '/profile/$username'
    | '/puzzles/storm'
    | '/study/$studyId'
    | '/tactics/$theme'
    | '/admin/'
    | '/assistant/'
    | '/coaches/'
    | '/endgame/'
    | '/learn/'
    | '/lessons/'
    | '/openings/'
    | '/puzzles/'
    | '/study/'
    | '/tactics/'
    | '/admin/users/$userId'
    | '/embed/$kind/$token'
    | '/puzzles/daily/$date'
    | '/admin/users/'
    | '/api/public/paystack/webhook'
    | '/api/public/v1/tournaments'
    | '/api/public/v1/webhooks'
    | '/api/public/v1/classes/session'
    | '/api/public/v1/correspondence/sweep'
    | '/api/public/v1/embed/token'
    | '/api/public/v1/webhooks/$id'
    | '/api/public/v1/webhooks/retry-sweep'
    | '/api/public/v1/embed/token/$token'
    | '/api/public/v1/tournaments/$id/standings'
    | '/api/public/v1/users/$username/games'
    | '/api/public/v1/users/$username/rating'
    | '/api/public/v1/classes/session/$id/set-position'
    | '/api/public/v1/classes/session/$id/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  BillingRoute: typeof BillingRoute
  FeedRoute: typeof FeedRoute
  InsightsRoute: typeof InsightsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LobbyRoute: typeof LobbyRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ApiChatRoute: typeof ApiChatRoute
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  CoachesCoachIdRoute: typeof CoachesCoachIdRoute
  CoachingDashboardRoute: typeof CoachingDashboardRoute
  EndgameIdRoute: typeof EndgameIdRoute
  LearnTutorialIdRoute: typeof LearnTutorialIdRoute
  LessonsIdRoute: typeof LessonsIdRoute
  OpeningsEcoRoute: typeof OpeningsEcoRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  PuzzlesStormRoute: typeof PuzzlesStormRoute
  StudyStudyIdRoute: typeof StudyStudyIdRoute
  TacticsThemeRoute: typeof TacticsThemeRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
  EndgameIndexRoute: typeof EndgameIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  OpeningsIndexRoute: typeof OpeningsIndexRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  StudyIndexRoute: typeof StudyIndexRoute
  TacticsIndexRoute: typeof TacticsIndexRoute
  EmbedKindTokenRoute: typeof EmbedKindTokenRoute
  PuzzlesDailyDateRoute: typeof PuzzlesDailyDateRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicV1TournamentsRoute: typeof ApiPublicV1TournamentsRouteWithChildren
  ApiPublicV1WebhooksRoute: typeof ApiPublicV1WebhooksRouteWithChildren
  ApiPublicV1ClassesSessionRoute: typeof ApiPublicV1ClassesSessionRouteWithChildren
  ApiPublicV1CorrespondenceSweepRoute: typeof ApiPublicV1CorrespondenceSweepRoute
  ApiPublicV1EmbedTokenRoute: typeof ApiPublicV1EmbedTokenRouteWithChildren
  ApiPublicV1UsersUsernameGamesRoute: typeof ApiPublicV1UsersUsernameGamesRoute
  ApiPublicV1UsersUsernameRatingRoute: typeof ApiPublicV1UsersUsernameRatingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-dashboard': {
      id: '/api-dashboard'
      path: '/api-dashboard'
      fullPath: '/api-dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tactics/': {
      id: '/tactics/'
      path: '/tactics'
      fullPath: '/tactics/'
      preLoaderRoute: typeof TacticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/': {
      id: '/openings/'
      path: '/openings'
      fullPath: '/openings/'
      preLoaderRoute: typeof OpeningsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgame/': {
      id: '/endgame/'
      path: '/endgame'
      fullPath: '/endgame/'
      preLoaderRoute: typeof EndgameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tactics/$theme': {
      id: '/tactics/$theme'
      path: '/tactics/$theme'
      fullPath: '/tactics/$theme'
      preLoaderRoute: typeof TacticsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$studyId': {
      id: '/study/$studyId'
      path: '/study/$studyId'
      fullPath: '/study/$studyId'
      preLoaderRoute: typeof StudyStudyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/storm': {
      id: '/puzzles/storm'
      path: '/puzzles/storm'
      fullPath: '/puzzles/storm'
      preLoaderRoute: typeof PuzzlesStormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings/$eco': {
      id: '/openings/$eco'
      path: '/openings/$eco'
      fullPath: '/openings/$eco'
      preLoaderRoute: typeof OpeningsEcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$id': {
      id: '/lessons/$id'
      path: '/lessons/$id'
      fullPath: '/lessons/$id'
      preLoaderRoute: typeof LessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$tutorialId': {
      id: '/learn/$tutorialId'
      path: '/learn/$tutorialId'
      fullPath: '/learn/$tutorialId'
      preLoaderRoute: typeof LearnTutorialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endgame/$id': {
      id: '/endgame/$id'
      path: '/endgame/$id'
      fullPath: '/endgame/$id'
      preLoaderRoute: typeof EndgameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching/dashboard': {
      id: '/coaching/dashboard'
      path: '/coaching/dashboard'
      fullPath: '/coaching/dashboard'
      preLoaderRoute: typeof CoachingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$coachId': {
      id: '/coaches/$coachId'
      path: '/coaches/$coachId'
      fullPath: '/coaches/$coachId'
      preLoaderRoute: typeof CoachesCoachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coaches': {
      id: '/admin/coaches'
      path: '/coaches'
      fullPath: '/admin/coaches'
      preLoaderRoute: typeof AdminCoachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/puzzles/daily/$date': {
      id: '/puzzles/daily/$date'
      path: '/puzzles/daily/$date'
      fullPath: '/puzzles/daily/$date'
      preLoaderRoute: typeof PuzzlesDailyDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$kind/$token': {
      id: '/embed/$kind/$token'
      path: '/embed/$kind/$token'
      fullPath: '/embed/$kind/$token'
      preLoaderRoute: typeof EmbedKindTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/v1/webhooks': {
      id: '/api/public/v1/webhooks'
      path: '/api/public/v1/webhooks'
      fullPath: '/api/public/v1/webhooks'
      preLoaderRoute: typeof ApiPublicV1WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tournaments': {
      id: '/api/public/v1/tournaments'
      path: '/api/public/v1/tournaments'
      fullPath: '/api/public/v1/tournaments'
      preLoaderRoute: typeof ApiPublicV1TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack/webhook': {
      id: '/api/public/paystack/webhook'
      path: '/api/public/paystack/webhook'
      fullPath: '/api/public/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/webhooks/retry-sweep': {
      id: '/api/public/v1/webhooks/retry-sweep'
      path: '/retry-sweep'
      fullPath: '/api/public/v1/webhooks/retry-sweep'
      preLoaderRoute: typeof ApiPublicV1WebhooksRetrySweepRouteImport
      parentRoute: typeof ApiPublicV1WebhooksRoute
    }
    '/api/public/v1/webhooks/$id': {
      id: '/api/public/v1/webhooks/$id'
      path: '/$id'
      fullPath: '/api/public/v1/webhooks/$id'
      preLoaderRoute: typeof ApiPublicV1WebhooksIdRouteImport
      parentRoute: typeof ApiPublicV1WebhooksRoute
    }
    '/api/public/v1/embed/token': {
      id: '/api/public/v1/embed/token'
      path: '/api/public/v1/embed/token'
      fullPath: '/api/public/v1/embed/token'
      preLoaderRoute: typeof ApiPublicV1EmbedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/correspondence/sweep': {
      id: '/api/public/v1/correspondence/sweep'
      path: '/api/public/v1/correspondence/sweep'
      fullPath: '/api/public/v1/correspondence/sweep'
      preLoaderRoute: typeof ApiPublicV1CorrespondenceSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/classes/session': {
      id: '/api/public/v1/classes/session'
      path: '/api/public/v1/classes/session'
      fullPath: '/api/public/v1/classes/session'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/users/$username/rating': {
      id: '/api/public/v1/users/$username/rating'
      path: '/api/public/v1/users/$username/rating'
      fullPath: '/api/public/v1/users/$username/rating'
      preLoaderRoute: typeof ApiPublicV1UsersUsernameRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/users/$username/games': {
      id: '/api/public/v1/users/$username/games'
      path: '/api/public/v1/users/$username/games'
      fullPath: '/api/public/v1/users/$username/games'
      preLoaderRoute: typeof ApiPublicV1UsersUsernameGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/tournaments/$id/standings': {
      id: '/api/public/v1/tournaments/$id/standings'
      path: '/$id/standings'
      fullPath: '/api/public/v1/tournaments/$id/standings'
      preLoaderRoute: typeof ApiPublicV1TournamentsIdStandingsRouteImport
      parentRoute: typeof ApiPublicV1TournamentsRoute
    }
    '/api/public/v1/embed/token/$token': {
      id: '/api/public/v1/embed/token/$token'
      path: '/$token'
      fullPath: '/api/public/v1/embed/token/$token'
      preLoaderRoute: typeof ApiPublicV1EmbedTokenTokenRouteImport
      parentRoute: typeof ApiPublicV1EmbedTokenRoute
    }
    '/api/public/v1/classes/session/$id/students': {
      id: '/api/public/v1/classes/session/$id/students'
      path: '/$id/students'
      fullPath: '/api/public/v1/classes/session/$id/students'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionIdStudentsRouteImport
      parentRoute: typeof ApiPublicV1ClassesSessionRoute
    }
    '/api/public/v1/classes/session/$id/set-position': {
      id: '/api/public/v1/classes/session/$id/set-position'
      path: '/$id/set-position'
      fullPath: '/api/public/v1/classes/session/$id/set-position'
      preLoaderRoute: typeof ApiPublicV1ClassesSessionIdSetPositionRouteImport
      parentRoute: typeof ApiPublicV1ClassesSessionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCoachesRoute: typeof AdminCoachesRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCoachesRoute: AdminCoachesRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminOrgsRoute: AdminOrgsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiPublicV1TournamentsRouteChildren {
  ApiPublicV1TournamentsIdStandingsRoute: typeof ApiPublicV1TournamentsIdStandingsRoute
}

const ApiPublicV1TournamentsRouteChildren: ApiPublicV1TournamentsRouteChildren =
  {
    ApiPublicV1TournamentsIdStandingsRoute:
      ApiPublicV1TournamentsIdStandingsRoute,
  }

const ApiPublicV1TournamentsRouteWithChildren =
  ApiPublicV1TournamentsRoute._addFileChildren(
    ApiPublicV1TournamentsRouteChildren,
  )

interface ApiPublicV1WebhooksRouteChildren {
  ApiPublicV1WebhooksIdRoute: typeof ApiPublicV1WebhooksIdRoute
  ApiPublicV1WebhooksRetrySweepRoute: typeof ApiPublicV1WebhooksRetrySweepRoute
}

const ApiPublicV1WebhooksRouteChildren: ApiPublicV1WebhooksRouteChildren = {
  ApiPublicV1WebhooksIdRoute: ApiPublicV1WebhooksIdRoute,
  ApiPublicV1WebhooksRetrySweepRoute: ApiPublicV1WebhooksRetrySweepRoute,
}

const ApiPublicV1WebhooksRouteWithChildren =
  ApiPublicV1WebhooksRoute._addFileChildren(ApiPublicV1WebhooksRouteChildren)

interface ApiPublicV1ClassesSessionRouteChildren {
  ApiPublicV1ClassesSessionIdSetPositionRoute: typeof ApiPublicV1ClassesSessionIdSetPositionRoute
  ApiPublicV1ClassesSessionIdStudentsRoute: typeof ApiPublicV1ClassesSessionIdStudentsRoute
}

const ApiPublicV1ClassesSessionRouteChildren: ApiPublicV1ClassesSessionRouteChildren =
  {
    ApiPublicV1ClassesSessionIdSetPositionRoute:
      ApiPublicV1ClassesSessionIdSetPositionRoute,
    ApiPublicV1ClassesSessionIdStudentsRoute:
      ApiPublicV1ClassesSessionIdStudentsRoute,
  }

const ApiPublicV1ClassesSessionRouteWithChildren =
  ApiPublicV1ClassesSessionRoute._addFileChildren(
    ApiPublicV1ClassesSessionRouteChildren,
  )

interface ApiPublicV1EmbedTokenRouteChildren {
  ApiPublicV1EmbedTokenTokenRoute: typeof ApiPublicV1EmbedTokenTokenRoute
}

const ApiPublicV1EmbedTokenRouteChildren: ApiPublicV1EmbedTokenRouteChildren = {
  ApiPublicV1EmbedTokenTokenRoute: ApiPublicV1EmbedTokenTokenRoute,
}

const ApiPublicV1EmbedTokenRouteWithChildren =
  ApiPublicV1EmbedTokenRoute._addFileChildren(
    ApiPublicV1EmbedTokenRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  BillingRoute: BillingRoute,
  FeedRoute: FeedRoute,
  InsightsRoute: InsightsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LobbyRoute: LobbyRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ApiChatRoute: ApiChatRoute,
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  CoachesCoachIdRoute: CoachesCoachIdRoute,
  CoachingDashboardRoute: CoachingDashboardRoute,
  EndgameIdRoute: EndgameIdRoute,
  LearnTutorialIdRoute: LearnTutorialIdRoute,
  LessonsIdRoute: LessonsIdRoute,
  OpeningsEcoRoute: OpeningsEcoRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  PuzzlesStormRoute: PuzzlesStormRoute,
  StudyStudyIdRoute: StudyStudyIdRoute,
  TacticsThemeRoute: TacticsThemeRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  CoachesIndexRoute: CoachesIndexRoute,
  EndgameIndexRoute: EndgameIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  OpeningsIndexRoute: OpeningsIndexRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  StudyIndexRoute: StudyIndexRoute,
  TacticsIndexRoute: TacticsIndexRoute,
  EmbedKindTokenRoute: EmbedKindTokenRoute,
  PuzzlesDailyDateRoute: PuzzlesDailyDateRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicV1TournamentsRoute: ApiPublicV1TournamentsRouteWithChildren,
  ApiPublicV1WebhooksRoute: ApiPublicV1WebhooksRouteWithChildren,
  ApiPublicV1ClassesSessionRoute: ApiPublicV1ClassesSessionRouteWithChildren,
  ApiPublicV1CorrespondenceSweepRoute: ApiPublicV1CorrespondenceSweepRoute,
  ApiPublicV1EmbedTokenRoute: ApiPublicV1EmbedTokenRouteWithChildren,
  ApiPublicV1UsersUsernameGamesRoute: ApiPublicV1UsersUsernameGamesRoute,
  ApiPublicV1UsersUsernameRatingRoute: ApiPublicV1UsersUsernameRatingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
